# Terraform github actions docs:
# https://learn.hashicorp.com/tutorials/terraform/github-actions
name: check

# Runs when we push changes to any go file under the go/ directory.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# included software: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
# - packer 1.8.0
jobs:
  check:
    name: "Packer and Terraform check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Runs packer and terraform validate
        run: make check
